name: build
on:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write
jobs:
  build:
    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: '1.6.10'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        nim compile -d:ssl -d:release ./prices.nim
        mv prices prices-${{ matrix.os }}
    - uses: actions/upload-artifact@v3
      with:
        name: prices-${{ matrix.os }}
        path: prices-${{ matrix.os }}

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v3
    - run: ls -al
    - uses: softprops/action-gh-release@v1
      with:
        files: |
          prices-*
